apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hjsulgdvg-python 
  janus-idp.io/tekton: hjsulgdvg-python
  backstage.io/kubernetes-id: hjsulgdvg-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hjsulgdvg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml